class RankData {
  final String name;
  final List<String> songIds;
  final List<int> levelIndexes;
  final int initialHp;
  final int greatDamage;
  final int goodDamage;
  final int missDamage;
  final int healAmount;

  RankData({
    required this.name,
    required this.songIds,
    required this.levelIndexes,
    required this.initialHp,
    required this.greatDamage,
    required this.goodDamage,
    required this.missDamage,
    required this.healAmount,
  });
}

class RankListService {
  List<String> getRankOptions() {
    return [
      '初段',
      '二段',
      '三段',
      '四段',
      '五段',
      '六段',
      '七段',
      '八段',
      '九段',
      '十段',
      '真初段',
      '真二段',
      '真三段',
      '真四段',
      '真五段',
      '真六段',
      '真七段',
      '真八段',
      '真九段',
      '真十段',
      '真皆传',
      '里皆传',
    ];
  }

  RankData? getRankData(String rankName) {
    final rankDataMap = {
      '初段': RankData(
        name: '初段',
        songIds: ['10256', '11052', '10319', '617'],
        levelIndexes: [0, 0, 0, 0],
        initialHp: 350,
        greatDamage: 0,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 20,
      ),
      '二段': RankData(
        name: '二段',
        songIds: ['11764', '11136', '11265', '11697'],
        levelIndexes: [1, 1, 1, 1],
        initialHp: 350,
        greatDamage: 0,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 20,
      ),
      '三段': RankData(
        name: '三段',
        songIds: ['11701', '11411', '11491', '11638'],
        levelIndexes: [1, 1, 1, 1],
        initialHp: 600,
        greatDamage: 1,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '四段': RankData(
        name: '四段',
        songIds: ['11698', '11276', '10535', '417'],
        levelIndexes: [2, 2, 2, 2],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '五段': RankData(
        name: '五段',
        songIds: ['579', '11003', '11333', '11770'],
        levelIndexes: [2, 2, 2, 2],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '六段': RankData(
        name: '六段',
        songIds: ['439', '11405', '432', '11272'],
        levelIndexes: [2, 2, 2, 3],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '七段': RankData(
        name: '七段',
        songIds: ['11271', '634', '11580', '11767'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 50,
      ),
      '八段': RankData(
        name: '八段',
        songIds: ['11017', '11048', '11615', '11512'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 700,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 20,
      ),
      '九段': RankData(
        name: '九段',
        songIds: ['11699', '11141', '798', '11496'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 800,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 30,
      ),
      '十段': RankData(
        name: '十段',
        songIds: ['840', '11207', '11412', '227'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 900,
        greatDamage: 2,
        goodDamage: 2,
        missDamage: 5,
        healAmount: 30,
      ),
      '真初段': RankData(
        name: '真初段',
        songIds: ['11010', '11133', '759', '136'],
        levelIndexes: [3, 3, 3, 2],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真二段': RankData(
        name: '真二段',
        songIds: ['791', '11350', '191', '11532'],
        levelIndexes: [3, 3, 2, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真三段': RankData(
        name: '真三段',
        songIds: ['11599', '794', '239', '709'],
        levelIndexes: [3, 3, 2, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真四段': RankData(
        name: '真四段',
        songIds: ['11715', '581', '204', '453'],
        levelIndexes: [3, 2, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真五段': RankData(
        name: '真五段',
        songIds: ['11583', '11653', '448', '673'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真六段': RankData(
        name: '真六段',
        songIds: ['11316', '11710', '11177', '700'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真七段': RankData(
        name: '真七段',
        songIds: ['11460', '11208', '451', '11413'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真八段': RankData(
        name: '真八段',
        songIds: ['766', '11213', '24', '556'],
        levelIndexes: [3, 3, 4, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真九段': RankData(
        name: '真九段',
        songIds: ['11675', '11618', '589', '11687'],
        levelIndexes: [3, 3, 4, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真十段': RankData(
        name: '真十段',
        songIds: ['11295', '11026', '11470', '11619'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 10,
      ),
      '真皆传': RankData(
        name: '真皆传',
        songIds: ['11223', '11745', '11311', '11753'],
        levelIndexes: [3, 3, 3, 3],
        initialHp: 50,
        greatDamage: 2,
        goodDamage: 3,
        missDamage: 5,
        healAmount: 5,
      ),
      '里皆传': RankData(
        name: '里皆传',
        songIds: ['834', '11612', '11662', '11663'],
        levelIndexes: [4, 3, 3, 4],
        initialHp: 10,
        greatDamage: 1,
        goodDamage: 3,
        missDamage: 10,
        healAmount: 0,
      ),
    };

    return rankDataMap[rankName];
  }
}