/* 此文件由 scripts/generate-phigros-reference-avatar-assets.mjs 根据原项目头像目录生成。 */
export const PHIGROS_REFERENCE_AVATAR_SOURCES: Readonly<Record<string, number>> = {
  "-SURREALISM-": require("../../../assets/phigros-b30-reference/avatar/-SURREALISM-.png") as number,
  "[PRAW]": require("../../../assets/phigros-b30-reference/avatar/[PRAW].png") as number,
  "瓷岁-Special": require("../../../assets/phigros-b30-reference/avatar/瓷岁-Special.png") as number,
  "瓷岁1": require("../../../assets/phigros-b30-reference/avatar/瓷岁1.png") as number,
  "瓷岁2": require("../../../assets/phigros-b30-reference/avatar/瓷岁2.png") as number,
  "瓷岁3": require("../../../assets/phigros-b30-reference/avatar/瓷岁3.png") as number,
  "瓷岁4": require("../../../assets/phigros-b30-reference/avatar/瓷岁4.png") as number,
  "瓷岁5": require("../../../assets/phigros-b30-reference/avatar/瓷岁5.png") as number,
  "瓷岁6": require("../../../assets/phigros-b30-reference/avatar/瓷岁6.png") as number,
  "瓷岁7": require("../../../assets/phigros-b30-reference/avatar/瓷岁7.png") as number,
  "风屿": require("../../../assets/phigros-b30-reference/avatar/风屿.png") as number,
  "光": require("../../../assets/phigros-b30-reference/avatar/光.png") as number,
  "華灯爱1": require("../../../assets/phigros-b30-reference/avatar/華灯爱1.png") as number,
  "華灯爱2": require("../../../assets/phigros-b30-reference/avatar/華灯爱2.png") as number,
  "混乱-Confusion": require("../../../assets/phigros-b30-reference/avatar/混乱-Confusion.png") as number,
  "鸠-一周年相聚": require("../../../assets/phigros-b30-reference/avatar/鸠-一周年相聚.png") as number,
  "鸠-AprilFool": require("../../../assets/phigros-b30-reference/avatar/鸠-AprilFool.png") as number,
  "开心病1": require("../../../assets/phigros-b30-reference/avatar/开心病1.png") as number,
  "开心病2": require("../../../assets/phigros-b30-reference/avatar/开心病2.png") as number,
  "狂喜蘭舞1": require("../../../assets/phigros-b30-reference/avatar/狂喜蘭舞1.png") as number,
  "狂喜蘭舞2": require("../../../assets/phigros-b30-reference/avatar/狂喜蘭舞2.png") as number,
  "青芽": require("../../../assets/phigros-b30-reference/avatar/青芽.png") as number,
  "青芽-Special": require("../../../assets/phigros-b30-reference/avatar/青芽-Special.png") as number,
  "水青-一周年相聚": require("../../../assets/phigros-b30-reference/avatar/水青-一周年相聚.png") as number,
  "万吨匿名信": require("../../../assets/phigros-b30-reference/avatar/万吨匿名信.png") as number,
  "萤火虫の怨1": require("../../../assets/phigros-b30-reference/avatar/萤火虫の怨1.png") as number,
  "萤火虫の怨2": require("../../../assets/phigros-b30-reference/avatar/萤火虫の怨2.png") as number,
  "云女孩": require("../../../assets/phigros-b30-reference/avatar/云女孩.png") as number,
  "云女孩 extra 1 -by 御坂果子": require("../../../assets/phigros-b30-reference/avatar/云女孩 extra 1 -by 御坂果子.png") as number,
  "盏茗-Special": require("../../../assets/phigros-b30-reference/avatar/盏茗-Special.png") as number,
  "盏茗1": require("../../../assets/phigros-b30-reference/avatar/盏茗1.png") as number,
  "盏茗2": require("../../../assets/phigros-b30-reference/avatar/盏茗2.png") as number,
  "盏茗3": require("../../../assets/phigros-b30-reference/avatar/盏茗3.png") as number,
  "Alkaid": require("../../../assets/phigros-b30-reference/avatar/Alkaid.png") as number,
  "Aphasia": require("../../../assets/phigros-b30-reference/avatar/Aphasia.png") as number,
  "Artificial Existence": require("../../../assets/phigros-b30-reference/avatar/Artificial Existence.png") as number,
  "Bonus Time": require("../../../assets/phigros-b30-reference/avatar/Bonus Time.png") as number,
  "Burn": require("../../../assets/phigros-b30-reference/avatar/Burn.png") as number,
  "Cereris1": require("../../../assets/phigros-b30-reference/avatar/Cereris1.png") as number,
  "Cereris2": require("../../../assets/phigros-b30-reference/avatar/Cereris2.png") as number,
  "Cereris3": require("../../../assets/phigros-b30-reference/avatar/Cereris3.png") as number,
  "Christmas -2019": require("../../../assets/phigros-b30-reference/avatar/Christmas -2019.png") as number,
  "Cipher1": require("../../../assets/phigros-b30-reference/avatar/Cipher1.png") as number,
  "Class Memories": require("../../../assets/phigros-b30-reference/avatar/Class Memories.png") as number,
  "Credits": require("../../../assets/phigros-b30-reference/avatar/Credits.png") as number,
  "Dash": require("../../../assets/phigros-b30-reference/avatar/Dash.png") as number,
  "dB doll": require("../../../assets/phigros-b30-reference/avatar/dB doll.png") as number,
  "Dlyrotz": require("../../../assets/phigros-b30-reference/avatar/Dlyrotz.png") as number,
  "Doppelganger1": require("../../../assets/phigros-b30-reference/avatar/Doppelganger1.png") as number,
  "Doppelganger2": require("../../../assets/phigros-b30-reference/avatar/Doppelganger2.png") as number,
  "Drop it": require("../../../assets/phigros-b30-reference/avatar/Drop it.png") as number,
  "Energy Synergy Matrix1": require("../../../assets/phigros-b30-reference/avatar/Energy Synergy Matrix1.png") as number,
  "Energy Synergy Matrix2": require("../../../assets/phigros-b30-reference/avatar/Energy Synergy Matrix2.png") as number,
  "Energy Synergy Matrix3": require("../../../assets/phigros-b30-reference/avatar/Energy Synergy Matrix3.png") as number,
  "Engine x Start!! (melody mix)": require("../../../assets/phigros-b30-reference/avatar/Engine x Start!! (melody mix).png") as number,
  "Engine x Start!! extra 1 -by cycats": require("../../../assets/phigros-b30-reference/avatar/Engine x Start!! extra 1 -by cycats.png") as number,
  "Eradication Catastrophe": require("../../../assets/phigros-b30-reference/avatar/Eradication Catastrophe.png") as number,
  "Feast远东之宴-Special1": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴-Special1.png") as number,
  "Feast远东之宴-Special2": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴-Special2.png") as number,
  "Feast远东之宴1": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴1.png") as number,
  "Feast远东之宴2": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴2.png") as number,
  "Feast远东之宴3": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴3.png") as number,
  "Feast远东之宴4": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴4.png") as number,
  "Feast远东之宴5": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴5.png") as number,
  "Feast远东之宴6": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴6.png") as number,
  "Feast远东之宴7": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴7.png") as number,
  "Feast远东之宴8": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴8.png") as number,
  "Feast远东之宴9": require("../../../assets/phigros-b30-reference/avatar/Feast远东之宴9.png") as number,
  "Find_Me": require("../../../assets/phigros-b30-reference/avatar/Find_Me.png") as number,
  "FULi AUTO SHOOTER": require("../../../assets/phigros-b30-reference/avatar/FULi AUTO SHOOTER.png") as number,
  "FULi AUTO SHOOTER extra 1 -by cycats": require("../../../assets/phigros-b30-reference/avatar/FULi AUTO SHOOTER extra 1 -by cycats.png") as number,
  "Geopelia 1 -by cycats": require("../../../assets/phigros-b30-reference/avatar/Geopelia 1 -by cycats.png") as number,
  "Geopelia 2 -by cycats": require("../../../assets/phigros-b30-reference/avatar/Geopelia 2 -by cycats.png") as number,
  "Geopelia 3 -by 何呵": require("../../../assets/phigros-b30-reference/avatar/Geopelia 3 -by 何呵.png") as number,
  "Geopelia in WEPLAY -by 海产": require("../../../assets/phigros-b30-reference/avatar/Geopelia in WEPLAY -by 海产.png") as number,
  "Gino-AprilFool": require("../../../assets/phigros-b30-reference/avatar/Gino-AprilFool.png") as number,
  "Glaciaxion": require("../../../assets/phigros-b30-reference/avatar/Glaciaxion.png") as number,
  "HumaN": require("../../../assets/phigros-b30-reference/avatar/HumaN.png") as number,
  "Indelible Scar": require("../../../assets/phigros-b30-reference/avatar/Indelible Scar.png") as number,
  "Introduction": require("../../../assets/phigros-b30-reference/avatar/Introduction.png") as number,
  "Khronostasis Katharsis": require("../../../assets/phigros-b30-reference/avatar/Khronostasis Katharsis.png") as number,
  "MARENOL": require("../../../assets/phigros-b30-reference/avatar/MARENOL.png") as number,
  "Marenol extra 1 -by 喵n葵": require("../../../assets/phigros-b30-reference/avatar/Marenol extra 1 -by 喵n葵.png") as number,
  "Non-Melodic Ragez (MUG Edit)": require("../../../assets/phigros-b30-reference/avatar/Non-Melodic Ragez (MUG Edit).png") as number,
  "Non-Melodic Ragez extra 1 -by cycats": require("../../../assets/phigros-b30-reference/avatar/Non-Melodic Ragez extra 1 -by cycats.png") as number,
  "OblivionPHIN": require("../../../assets/phigros-b30-reference/avatar/OblivionPHIN.png") as number,
  "Para": require("../../../assets/phigros-b30-reference/avatar/Para.png") as number,
  "Pixel Rebelz1": require("../../../assets/phigros-b30-reference/avatar/Pixel Rebelz1.png") as number,
  "Pixel Rebelz2": require("../../../assets/phigros-b30-reference/avatar/Pixel Rebelz2.png") as number,
  "Pixel Rebelz3": require("../../../assets/phigros-b30-reference/avatar/Pixel Rebelz3.png") as number,
  "ripper": require("../../../assets/phigros-b30-reference/avatar/ripper.png") as number,
  "RIPPER extra 1 -by cycats": require("../../../assets/phigros-b30-reference/avatar/RIPPER extra 1 -by cycats.png") as number,
  "RIPPER extra 2 -by 何呵": require("../../../assets/phigros-b30-reference/avatar/RIPPER extra 2 -by 何呵.png") as number,
  "Sein": require("../../../assets/phigros-b30-reference/avatar/Sein.png") as number,
  "ShineAfter-鸠-普通": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-鸠-普通.png") as number,
  "ShineAfter-鸠-曲绘Ver": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-鸠-曲绘Ver.png") as number,
  "ShineAfter-鸠-Special": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-鸠-Special.png") as number,
  "ShineAfter-鸠和水青-Special": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-鸠和水青-Special.png") as number,
  "ShineAfter-水青-普通": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-水青-普通.png") as number,
  "ShineAfter-水青-曲绘Ver": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-水青-曲绘Ver.png") as number,
  "ShineAfter-水青-Special": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-水青-Special.png") as number,
  "ShineAfter-水青-Special2": require("../../../assets/phigros-b30-reference/avatar/ShineAfter-水青-Special2.png") as number,
  "Snow Desert": require("../../../assets/phigros-b30-reference/avatar/Snow Desert.png") as number,
  "Sparkle New Life": require("../../../assets/phigros-b30-reference/avatar/Sparkle New Life.png") as number,
  "Sultan Rage": require("../../../assets/phigros-b30-reference/avatar/Sultan Rage.png") as number,
  "Winter ↑cube↓": require("../../../assets/phigros-b30-reference/avatar/Winter ↑cube↓.png") as number,
  "Xenolith": require("../../../assets/phigros-b30-reference/avatar/Xenolith.png") as number,
  "もぺもぺ1": require("../../../assets/phigros-b30-reference/avatar/もぺもぺ1.png") as number,
  "もぺもぺ2": require("../../../assets/phigros-b30-reference/avatar/もぺもぺ2.png") as number,
};

export const PHIGROS_REFERENCE_AVATAR_KEYS = Object.freeze(Object.keys(PHIGROS_REFERENCE_AVATAR_SOURCES));
