import { StyleSheet } from 'react-native';

export const uploadDataSheetStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F2F2F7' },
  grabber: {
    alignSelf: 'center',
    width: 36,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
    marginTop: 8,
    marginBottom: 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  title: { color: '#111827', fontSize: 18, fontWeight: '700' },
  closeHit: { paddingVertical: 4, paddingHorizontal: 4 },
  close: { color: '#246BFD', fontSize: 16, fontWeight: '600' },
  softPressed: { opacity: 0.7 },
  content: { paddingHorizontal: 20, paddingBottom: 28, gap: 12 },
  sectionLabel: { color: '#6B7280', fontSize: 13, fontWeight: '600', marginTop: 4 },
  friendCodeBlock: { gap: 8 },
  friendCodeRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  friendCodeInput: { flex: 1 },
  historyButton: {
    minHeight: 48,
    minWidth: 64,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyDropdown: {
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 10,
  },
  historyRowBorder: { borderTopWidth: StyleSheet.hairlineWidth },
  historySelect: { flex: 1, gap: 2, paddingVertical: 2 },
  historyCode: { fontSize: 15, fontWeight: '600', letterSpacing: 1 },
  historyMeta: { fontSize: 12 },
  historyDelete: {
    minHeight: 36,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyDeleteText: { fontSize: 13, fontWeight: '700' },
  input: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 17,
    color: '#111827',
    letterSpacing: 1,
  },
  qrInput: {
    letterSpacing: 0,
    minHeight: 72,
    textAlignVertical: 'top',
  },
  hint: { color: '#9CA3AF', fontSize: 12, lineHeight: 18 },
  qrActions: { flexDirection: 'row', gap: 8 },
  secondary: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { fontSize: 14, fontWeight: '700' },
  listCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    overflow: 'hidden',
  },
  empty: { color: '#6B7280', padding: 16 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  rowBorder: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#E5E7EB' },
  rowDisabled: { opacity: 0.55 },
  box: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  boxMark: { color: '#FFFFFF', fontSize: 14, fontWeight: '700', lineHeight: 16 },
  icon: { width: 36, height: 36, borderRadius: 8 },
  iconPlaceholder: { width: 36, height: 36, borderRadius: 8, backgroundColor: '#E5E7EB' },
  rowBody: { flex: 1, gap: 2 },
  rowTitle: { color: '#111827', fontSize: 16, fontWeight: '600' },
  rowSub: { color: '#6B7280', fontSize: 13 },
  rowWarn: { color: '#B45309', fontSize: 12, marginTop: 2 },
  primary: {
    marginTop: 8,
    backgroundColor: '#246BFD',
    borderRadius: 14,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryDisabled: { opacity: 0.55 },
  cancel: {
    backgroundColor: '#DC2626',
    borderRadius: 14,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  statusBox: {
    marginTop: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    gap: 6,
  },
  statusSpinner: { alignSelf: 'flex-start', marginBottom: 4 },
  statusText: { color: '#374151', fontSize: 14, lineHeight: 20 },
  statusBot: { color: '#6B7280', fontSize: 12, lineHeight: 18 },
  resultList: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 12, gap: 10 },
  resultRow: { gap: 3 },
  resultSuccess: { color: '#16803A', fontWeight: '700' },
  resultFailure: { color: '#B42318', fontWeight: '700' },
  resultDetail: { color: '#6B7280', fontSize: 12, lineHeight: 18 },
});
