import { StyleSheet } from 'react-native';

export const SIMAI_CHART_GAP = 12;

export const simaiSongDetailStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F7F8FA' },
  content: { paddingBottom: 48 },
  deferredPlaceholder: { minHeight: 180 },
  hero: { position: 'relative', backgroundColor: '#D9DEE7', overflow: 'hidden' },
  heroShade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: '48%' },
  heroCopy: { position: 'absolute', left: 18, right: 18, bottom: 20, gap: 2 },
  singleLine: { flexGrow: 0 },
  singleLineContent: { paddingRight: 18 },
  songId: { color: 'rgba(255,255,255,0.78)', fontSize: 12, fontWeight: '600', letterSpacing: 0.4 },
  title: { color: '#FFFFFF', fontSize: 30, lineHeight: 37, fontWeight: '900', letterSpacing: -0.6, textShadowColor: 'rgba(0,0,0,0.35)', textShadowRadius: 8 },
  artist: { color: 'rgba(255,255,255,0.9)', fontSize: 16, lineHeight: 23, fontWeight: '600' },
  headerButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  headerFloatingButton: { position: 'absolute', zIndex: 30, elevation: 30 },
  headerFavoriteActive: {},
  metadataTable: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: '#FFFFFF', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#D8DEE8', paddingHorizontal: 12, paddingVertical: 13, gap: 6 },
  metadataCellRoot: { minWidth: 0 },
  metadataCell: { minWidth: 0, paddingHorizontal: 6, gap: 5 },
  metadataLabel: { color: '#8A93A3', fontSize: 11, fontWeight: '700', lineHeight: 14 },
  switchPressed: { opacity: 0.58 },
  metadataValueBlock: { position: 'relative', minWidth: 0 },
  metadataValueMeasure: { position: 'absolute', left: 0, right: 0, opacity: 0, zIndex: -1 },
  metadataValue: { color: '#182130', fontSize: 13, lineHeight: 16, fontWeight: '700' },
  carouselRoot: { flexGrow: 0 },
  carouselScroll: { flexGrow: 0 },
  carousel: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 12, gap: SIMAI_CHART_GAP },
  noCharts: { padding: 20 },
  chartCard: { borderRadius: 24, borderWidth: 1, padding: 18, shadowColor: '#1A2232', shadowOffset: { width: 0, height: 7 }, shadowOpacity: 0.1, shadowRadius: 16, elevation: 4 },
  chartHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  chartIdentity: { alignItems: 'flex-start', gap: 7 },
  levelBlock: { alignItems: 'flex-end' },
  level: { color: '#172033', fontSize: 28, lineHeight: 31, fontWeight: '900' },
  constant: { color: '#667085', fontSize: 11, fontWeight: '600' },
  resultRow: { flexDirection: 'row', marginTop: 22 },
  resultMain: { flex: 1, alignItems: 'flex-start' },
  achievementLabel: { color: '#7D8797', fontSize: 12, fontWeight: '700', marginBottom: 2 },
  statusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, minHeight: 29, marginTop: 7 },
  chartDivider: { height: StyleSheet.hairlineWidth, backgroundColor: 'rgba(51,65,85,0.18)', marginVertical: 16 },
  chartMeta: { color: '#4C586A', fontSize: 12, lineHeight: 18 },
  notesTable: { marginTop: 9, borderWidth: StyleSheet.hairlineWidth, borderColor: 'rgba(76,88,106,0.28)', borderRadius: 9, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,0.38)' },
  notesAction: { borderRadius: 9 },
  notesActionPressed: { opacity: 0.62 },
  notesHint: { color: '#697386', fontSize: 9, lineHeight: 13, textAlign: 'center', marginTop: 4 },
  notesPlayerLabel: { fontSize: 11, fontWeight: '900', marginTop: 9, marginBottom: -4 },
  notesRow: { minHeight: 26, flexDirection: 'row', alignItems: 'center' },
  notesHeaderRow: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(76,88,106,0.22)' },
  notesCell: { flex: 1, minWidth: 0, textAlign: 'center' },
  notesHeader: { color: '#697386', fontSize: 8, fontWeight: '800' },
  notesValue: { color: '#253047', fontSize: 10, fontWeight: '800' },
  section: { fontWeight: '700', color: '#111827', marginBottom: 7 },
  body: { color: '#374151', lineHeight: 20 },
  meta: { color: '#6B7280', fontSize: 12 },
  details: { paddingHorizontal: 16, gap: 12, marginTop: 4 },
  scrollActionRoot: { flexGrow: 0 },
  action: { marginTop: 13, marginBottom: 10, borderWidth: 1, borderColor: '#667085', borderRadius: 11, padding: 10, alignItems: 'center', backgroundColor: 'transparent' },
  chartSearchAction: { marginTop: 0 },
  actionText: { fontWeight: '700' }
});
