class VersionListConstant {
  static const Set<String> standardVersions = {
    'maimai',
    'maimai PLUS',
    'maimai GreeN',
    'maimai GreeN PLUS',
    'maimai ORANGE',
    'maimai ORANGE PLUS',
    'maimai PiNK',
    'maimai PiNK PLUS',
    'maimai MURASAKi',
    'maimai MURASAKi PLUS',
    'maimai MiLK',
    'MiLK PLUS',
    'maimai FiNALE',
    'maimai でらっくす',
    'maimai でらっくす Splash',
    'maimai でらっくす UNiVERSE',
    'maimai でらっくす FESTiVAL',
    'maimai でらっくす BUDDiES',
    'maimai でらっくす PRiSM',
    'maimai でらっくす PRiSM PLUS',
  };

  static const Map<String, int> versionOrderMap = {
    'maimai': 1,
    'maimai PLUS': 2,
    'maimai GreeN': 3,
    'maimai GreeN PLUS': 4,
    'maimai ORANGE': 5,
    'maimai ORANGE PLUS': 6,
    'maimai PiNK': 7,
    'maimai PiNK PLUS': 8,
    'maimai MURASAKi': 9,
    'maimai MURASAKi PLUS': 10,
    'maimai MiLK': 11,
    'MiLK PLUS': 12,
    'maimai FiNALE': 13,
    'maimai でらっくす': 14,
    'maimai でらっくす Splash': 15,
    'maimai でらっくす UNiVERSE': 16,
    'maimai でらっくす FESTiVAL': 17,
    'maimai でらっくす BUDDiES': 18,
    'maimai でらっくす PRiSM': 19,
    'maimai でらっくす PRiSM PLUS': 20,
  };

  static const List<String> versionOrderList = [
    'maimai',
    'maimai PLUS',
    'maimai GreeN',
    'maimai GreeN PLUS',
    'maimai ORANGE',
    'maimai ORANGE PLUS',
    'maimai PiNK',
    'maimai PiNK PLUS',
    'maimai MURASAKi',
    'maimai MURASAKi PLUS',
    'maimai MiLK',
    'MiLK PLUS',
    'maimai FiNALE',
    'maimai でらっくす',
    'maimai でらっくす Splash',
    'maimai でらっくす UNiVERSE',
    'maimai でらっくす FESTiVAL',
    'maimai でらっくす BUDDiES',
    'maimai でらっくす PRiSM',
    'maimai でらっくす PRiSM PLUS',
  ];
}