/** 自动生成：舞萌谱面确认皮肤与正解音远程清单。勿手改；重新 HEAD 对象存储后覆盖。 */
export const MAIMAI_CHART_PREVIEW_ASSET_BASE =
  'https://rranker-maimai-data.cn-nb1.rains3.com/chart-preview' as const;

export type MaimaiChartPreviewSkinAsset = {
  readonly path: string;
  readonly url: string;
  readonly bytes: number;
};

export const MAIMAI_CHART_PREVIEW_ANSWER_SOUND = {
  path: 'answer.wav' as const,
  url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/answer.wav`,
  bytes: 35816,
} as const;

export const MAIMAI_CHART_PREVIEW_SKIN_ASSETS: readonly MaimaiChartPreviewSkinAsset[] = [
  { path: "HoldSkins/hold_break_mine_on.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_break_mine_on.png`, bytes: 9206 },
  { path: "HoldSkins/hold_break_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_break_mine.png`, bytes: 15508 },
  { path: "HoldSkins/hold_break_on.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_break_on.png`, bytes: 9443 },
  { path: "HoldSkins/hold_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_break.png`, bytes: 16505 },
  { path: "HoldSkins/hold_each_on.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_each_on.png`, bytes: 8580 },
  { path: "HoldSkins/hold_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_each.png`, bytes: 9334 },
  { path: "HoldSkins/hold_ex.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_ex.png`, bytes: 5773 },
  { path: "HoldSkins/hold_mine_on.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_mine_on.png`, bytes: 11683 },
  { path: "HoldSkins/hold_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_mine.png`, bytes: 9262 },
  { path: "HoldSkins/hold_off.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_off.png`, bytes: 9017 },
  { path: "HoldSkins/hold_on.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold_on.png`, bytes: 8260 },
  { path: "HoldSkins/hold.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/HoldSkins/hold.png`, bytes: 9489 },
  { path: "JudgeTextSkins/judge_text_break_2550.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/JudgeTextSkins/judge_text_break_2550.png`, bytes: 15261 },
  { path: "JudgeTextSkins/judge_text_break_2600.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/JudgeTextSkins/judge_text_break_2600.png`, bytes: 13236 },
  { path: "JudgeTextSkins/judge_text_cPerfect_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/JudgeTextSkins/judge_text_cPerfect_break.png`, bytes: 8436 },
  { path: "JudgeTextSkins/judge_text_cPerfect.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/JudgeTextSkins/judge_text_cPerfect.png`, bytes: 6338 },
  { path: "JudgeTextSkins/judge_text_perfect.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/JudgeTextSkins/judge_text_perfect.png`, bytes: 3446 },
  { path: "NoteGuideSkins/Break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Break.png`, bytes: 49259 },
  { path: "NoteGuideSkins/Each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Each.png`, bytes: 48869 },
  { path: "NoteGuideSkins/EachLine1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/EachLine1.png`, bytes: 9143 },
  { path: "NoteGuideSkins/EachLine2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/EachLine2.png`, bytes: 13085 },
  { path: "NoteGuideSkins/EachLine3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/EachLine3.png`, bytes: 18043 },
  { path: "NoteGuideSkins/EachLine4.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/EachLine4.png`, bytes: 32962 },
  { path: "NoteGuideSkins/Hold_Break_End.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Hold_Break_End.png`, bytes: 3821 },
  { path: "NoteGuideSkins/Hold_Each_End.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Hold_Each_End.png`, bytes: 2728 },
  { path: "NoteGuideSkins/Hold_End.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Hold_End.png`, bytes: 2803 },
  { path: "NoteGuideSkins/Hold_Mine_End.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Hold_Mine_End.png`, bytes: 2627 },
  { path: "NoteGuideSkins/Mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Mine.png`, bytes: 44411 },
  { path: "NoteGuideSkins/Normal.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Normal.png`, bytes: 48094 },
  { path: "NoteGuideSkins/Slide.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/NoteGuideSkins/Slide.png`, bytes: 43168 },
  { path: "outline.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/outline.png`, bytes: 89656 },
  { path: "SlideOKSkins/just_curv_l_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_curv_l_break.png`, bytes: 24716 },
  { path: "SlideOKSkins/just_curv_l.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_curv_l.png`, bytes: 19351 },
  { path: "SlideOKSkins/just_curv_r_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_curv_r_break.png`, bytes: 24466 },
  { path: "SlideOKSkins/just_curv_r.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_curv_r.png`, bytes: 19236 },
  { path: "SlideOKSkins/just_str_l_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_str_l_break.png`, bytes: 13445 },
  { path: "SlideOKSkins/just_str_l.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_str_l.png`, bytes: 10484 },
  { path: "SlideOKSkins/just_str_r_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_str_r_break.png`, bytes: 13367 },
  { path: "SlideOKSkins/just_str_r.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_str_r.png`, bytes: 10455 },
  { path: "SlideOKSkins/just_wifi_d_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_wifi_d_break.png`, bytes: 34244 },
  { path: "SlideOKSkins/just_wifi_d.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_wifi_d.png`, bytes: 31069 },
  { path: "SlideOKSkins/just_wifi_u_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_wifi_u_break.png`, bytes: 33988 },
  { path: "SlideOKSkins/just_wifi_u.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideOKSkins/just_wifi_u.png`, bytes: 29268 },
  { path: "SlideSkins/slide_break_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideSkins/slide_break_mine.png`, bytes: 7952 },
  { path: "SlideSkins/slide_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideSkins/slide_break.png`, bytes: 5956 },
  { path: "SlideSkins/slide_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideSkins/slide_each.png`, bytes: 1968 },
  { path: "SlideSkins/slide_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideSkins/slide_mine.png`, bytes: 2692 },
  { path: "SlideSkins/slide.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/SlideSkins/slide.png`, bytes: 1929 },
  { path: "StarSkins/star_break_double_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_break_double_mine.png`, bytes: 16569 },
  { path: "StarSkins/star_break_double.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_break_double.png`, bytes: 15290 },
  { path: "StarSkins/star_break_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_break_mine.png`, bytes: 13555 },
  { path: "StarSkins/star_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_break.png`, bytes: 13550 },
  { path: "StarSkins/star_double_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_double_mine.png`, bytes: 17475 },
  { path: "StarSkins/star_double.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_double.png`, bytes: 14626 },
  { path: "StarSkins/star_each_double.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_each_double.png`, bytes: 12953 },
  { path: "StarSkins/star_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_each.png`, bytes: 13627 },
  { path: "StarSkins/star_ex_double.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_ex_double.png`, bytes: 9624 },
  { path: "StarSkins/star_ex.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_ex.png`, bytes: 9969 },
  { path: "StarSkins/star_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star_mine.png`, bytes: 14584 },
  { path: "StarSkins/star.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/StarSkins/star.png`, bytes: 13702 },
  { path: "TapSkins/tap_break_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TapSkins/tap_break_mine.png`, bytes: 12085 },
  { path: "TapSkins/tap_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TapSkins/tap_break.png`, bytes: 11719 },
  { path: "TapSkins/tap_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TapSkins/tap_each.png`, bytes: 10053 },
  { path: "TapSkins/tap_ex.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TapSkins/tap_ex.png`, bytes: 7605 },
  { path: "TapSkins/tap_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TapSkins/tap_mine.png`, bytes: 9008 },
  { path: "TapSkins/tap.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TapSkins/tap.png`, bytes: 11636 },
  { path: "TouchHoldSkins/touchhold_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_0.png`, bytes: 6253 },
  { path: "TouchHoldSkins/touchhold_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_1.png`, bytes: 6394 },
  { path: "TouchHoldSkins/touchhold_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_2.png`, bytes: 5978 },
  { path: "TouchHoldSkins/touchhold_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_3.png`, bytes: 6359 },
  { path: "TouchHoldSkins/touchhold_border.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_border.png`, bytes: 18932 },
  { path: "TouchHoldSkins/touchhold_break_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_break_0.png`, bytes: 6253 },
  { path: "TouchHoldSkins/touchhold_break_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_break_1.png`, bytes: 6394 },
  { path: "TouchHoldSkins/touchhold_break_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_break_2.png`, bytes: 5978 },
  { path: "TouchHoldSkins/touchhold_break_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_break_3.png`, bytes: 6359 },
  { path: "TouchHoldSkins/touchhold_break_border.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_break_border.png`, bytes: 18932 },
  { path: "TouchHoldSkins/touchhold_break_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_break_mine.png`, bytes: 14842 },
  { path: "TouchHoldSkins/touchhold_mine_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_mine_0.png`, bytes: 6560 },
  { path: "TouchHoldSkins/touchhold_mine_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_mine_1.png`, bytes: 7077 },
  { path: "TouchHoldSkins/touchhold_mine_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_mine_2.png`, bytes: 6864 },
  { path: "TouchHoldSkins/touchhold_mine_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_mine_3.png`, bytes: 6409 },
  { path: "TouchHoldSkins/touchhold_off.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchHoldSkins/touchhold_off.png`, bytes: 14985 },
  { path: "TouchSkins/touch_border_2_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_border_2_each.png`, bytes: 9418 },
  { path: "TouchSkins/touch_border_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_border_2.png`, bytes: 9368 },
  { path: "TouchSkins/touch_border_3_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_border_3_each.png`, bytes: 12343 },
  { path: "TouchSkins/touch_border_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_border_3.png`, bytes: 12216 },
  { path: "TouchSkins/touch_break_border_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_border_2.png`, bytes: 11712 },
  { path: "TouchSkins/touch_break_border_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_border_3.png`, bytes: 14480 },
  { path: "TouchSkins/touch_break_mine_border_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_mine_border_2.png`, bytes: 9989 },
  { path: "TouchSkins/touch_break_mine_border_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_mine_border_3.png`, bytes: 12974 },
  { path: "TouchSkins/touch_break_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_mine.png`, bytes: 6054 },
  { path: "TouchSkins/touch_break_point_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_point_mine.png`, bytes: 1361 },
  { path: "TouchSkins/touch_break_point.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break_point.png`, bytes: 2649 },
  { path: "TouchSkins/touch_break.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_break.png`, bytes: 9509 },
  { path: "TouchSkins/touch_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_each.png`, bytes: 7314 },
  { path: "TouchSkins/touch_just.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_just.png`, bytes: 4518 },
  { path: "TouchSkins/touch_mine_border_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_mine_border_2.png`, bytes: 14818 },
  { path: "TouchSkins/touch_mine_border_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_mine_border_3.png`, bytes: 14695 },
  { path: "TouchSkins/touch_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_mine.png`, bytes: 8102 },
  { path: "TouchSkins/touch_point_each.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_point_each.png`, bytes: 1095 },
  { path: "TouchSkins/touch_point_mine.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_point_mine.png`, bytes: 1368 },
  { path: "TouchSkins/touch_point.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch_point.png`, bytes: 1108 },
  { path: "TouchSkins/touch.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/TouchSkins/touch.png`, bytes: 7540 },
  { path: "WifiSkins/wifi_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_0.png`, bytes: 3981 },
  { path: "WifiSkins/wifi_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_1.png`, bytes: 4581 },
  { path: "WifiSkins/wifi_10.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_10.png`, bytes: 16604 },
  { path: "WifiSkins/wifi_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_2.png`, bytes: 5603 },
  { path: "WifiSkins/wifi_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_3.png`, bytes: 6836 },
  { path: "WifiSkins/wifi_4.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_4.png`, bytes: 7080 },
  { path: "WifiSkins/wifi_5.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_5.png`, bytes: 9506 },
  { path: "WifiSkins/wifi_6.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_6.png`, bytes: 10374 },
  { path: "WifiSkins/wifi_7.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_7.png`, bytes: 10515 },
  { path: "WifiSkins/wifi_8.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_8.png`, bytes: 11042 },
  { path: "WifiSkins/wifi_9.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_9.png`, bytes: 11764 },
  { path: "WifiSkins/wifi_break_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_0.png`, bytes: 4085 },
  { path: "WifiSkins/wifi_break_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_1.png`, bytes: 4651 },
  { path: "WifiSkins/wifi_break_10.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_10.png`, bytes: 17007 },
  { path: "WifiSkins/wifi_break_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_2.png`, bytes: 5717 },
  { path: "WifiSkins/wifi_break_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_3.png`, bytes: 6972 },
  { path: "WifiSkins/wifi_break_4.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_4.png`, bytes: 7150 },
  { path: "WifiSkins/wifi_break_5.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_5.png`, bytes: 9672 },
  { path: "WifiSkins/wifi_break_6.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_6.png`, bytes: 10423 },
  { path: "WifiSkins/wifi_break_7.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_7.png`, bytes: 10546 },
  { path: "WifiSkins/wifi_break_8.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_8.png`, bytes: 11265 },
  { path: "WifiSkins/wifi_break_9.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_break_9.png`, bytes: 11804 },
  { path: "WifiSkins/wifi_each_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_0.png`, bytes: 4028 },
  { path: "WifiSkins/wifi_each_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_1.png`, bytes: 4604 },
  { path: "WifiSkins/wifi_each_10.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_10.png`, bytes: 16826 },
  { path: "WifiSkins/wifi_each_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_2.png`, bytes: 5646 },
  { path: "WifiSkins/wifi_each_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_3.png`, bytes: 6881 },
  { path: "WifiSkins/wifi_each_4.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_4.png`, bytes: 7073 },
  { path: "WifiSkins/wifi_each_5.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_5.png`, bytes: 9579 },
  { path: "WifiSkins/wifi_each_6.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_6.png`, bytes: 10400 },
  { path: "WifiSkins/wifi_each_7.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_7.png`, bytes: 10507 },
  { path: "WifiSkins/wifi_each_8.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_8.png`, bytes: 11293 },
  { path: "WifiSkins/wifi_each_9.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_each_9.png`, bytes: 11751 },
  { path: "WifiSkins/wifi_mine_0.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_0.png`, bytes: 7755 },
  { path: "WifiSkins/wifi_mine_1.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_1.png`, bytes: 11292 },
  { path: "WifiSkins/wifi_mine_10.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_10.png`, bytes: 56764 },
  { path: "WifiSkins/wifi_mine_2.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_2.png`, bytes: 15372 },
  { path: "WifiSkins/wifi_mine_3.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_3.png`, bytes: 19947 },
  { path: "WifiSkins/wifi_mine_4.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_4.png`, bytes: 23634 },
  { path: "WifiSkins/wifi_mine_5.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_5.png`, bytes: 29819 },
  { path: "WifiSkins/wifi_mine_6.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_6.png`, bytes: 36556 },
  { path: "WifiSkins/wifi_mine_7.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_7.png`, bytes: 40985 },
  { path: "WifiSkins/wifi_mine_8.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_8.png`, bytes: 47341 },
  { path: "WifiSkins/wifi_mine_9.png", url: `${MAIMAI_CHART_PREVIEW_ASSET_BASE}/WifiSkins/wifi_mine_9.png`, bytes: 51517 },
];
