import {
  applicationBestImageCardCss,
  escapeApplicationBestImageHtml,
  renderApplicationBestImageSection,
  type ApplicationBestImageCardPresentation,
} from './application-best-image-card';
import { buildBestImageCanvasRuntime } from './build-best-image-canvas-runtime';

export type FixedBestImageInput = {
  width: number;
  playerName: string;
  ratingDisplay: string;
  avatarUri?: string | null;
  sectionTitle: string;
  cards: readonly ApplicationBestImageCardPresentation[];
  dataSource: string;
};

function unit(width: number, value: number): number {
  return Math.max(1, Math.round(width * value / 1080));
}

/**
 * 固定 TopN / BestN 的薄页面壳。成绩卡 DOM 与三列布局只来自 Phigros 应用风格公共渲染器；
 * 调用方只提供已经本地化的素材与展示模型。
 */
export function buildFixedBestImageHtml(input: FixedBestImageInput): string {
  const width = Math.max(1, Math.round(input.width));
  const u = (value: number) => unit(width, value);
  const minimumHeight = Math.ceil(width * 0.75);
  const pageInset = u(43);
  const gridGap = u(14);
  const scoreCardPadding = u(12);
  const jacketSize = u(82);
  const avatar = input.avatarUri
    ? `<div class="avatar-shell"><img class="avatar" alt="" src="${escapeApplicationBestImageHtml(input.avatarUri)}"></div>`
    : '';
  const section = renderApplicationBestImageSection(input.sectionTitle, input.cards);
  const runtime = buildBestImageCanvasRuntime({ width, minimumHeight });

  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=${width}, initial-scale=1, maximum-scale=1, user-scalable=no">
  <style>
    *{box-sizing:border-box}
    html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#DDE3EC;font-family:system-ui,-apple-system,"Segoe UI","Noto Sans SC",sans-serif;-webkit-font-smoothing:antialiased;text-rendering:geometricPrecision}
    .preview-stage{position:fixed;inset:0;overflow:hidden;background:#DDE3EC}
    .canvas{position:absolute;left:0;top:0;width:${width}px;min-height:${minimumHeight}px;overflow:hidden;transform-origin:top left;background:linear-gradient(145deg,#EEF2F8 0%,#E7EDF5 52%,#F5F7FA 100%);color:#172033}
    .app-header{display:flex;align-items:center;gap:${u(16)}px;padding:${u(38)}px ${pageInset}px ${u(26)}px}
    .avatar-shell{width:${u(96)}px;height:${u(96)}px;flex:0 0 ${u(96)}px;overflow:hidden;border:${u(3)}px solid rgba(255,255,255,.92);border-radius:${u(18)}px;background:#DDE5F0;box-shadow:0 ${u(8)}px ${u(20)}px rgba(31,44,75,.18)}
    .avatar{display:block;width:100%;height:100%;object-fit:contain;object-position:center}
    .identity-line{display:flex;min-width:0;align-items:baseline;gap:${u(14)}px}
    .player-name{max-width:${u(720)}px;overflow:hidden;color:#1F2937;font:900 ${u(35)}px/1.15 system-ui,-apple-system,"Segoe UI",sans-serif;text-overflow:ellipsis;white-space:nowrap}
    .rating{display:inline-flex;flex:0 0 auto;align-items:baseline;gap:${u(7)}px;color:#4B5563;font:800 ${u(15)}px/1 system-ui,-apple-system,"Segoe UI",sans-serif;white-space:nowrap}
    .rating b{color:#172033;font-size:${u(21)}px;font-variant-numeric:tabular-nums}
    .scores-content{padding:0 ${pageInset}px ${u(36)}px}
    ${applicationBestImageCardCss({ width, gridGap, scoreCardPadding, jacketSize })}
    .image-footer{margin-top:${u(44)}px;text-align:center;color:rgba(60,70,90,.85);font:600 ${u(14)}px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}
    .image-footer>div{white-space:nowrap}
  </style>
</head>
<body>
  <div class="preview-stage">
    <main class="canvas" aria-label="${escapeApplicationBestImageHtml(input.sectionTitle)} 成绩图片预览">
      <header class="app-header" data-layout-content aria-label="玩家资料">
        ${avatar}
        <div class="identity-line"><strong class="player-name">${escapeApplicationBestImageHtml(input.playerName)}</strong><span class="rating">Rating <b>${escapeApplicationBestImageHtml(input.ratingDisplay)}</b></span></div>
      </header>
      <div class="scores-content" data-layout-content aria-label="成绩列表">
        ${section}
        <footer class="image-footer">
          <div>Designed by EgawaHokori. Data from ${escapeApplicationBestImageHtml(input.dataSource)}.</div>
          <div>Generated by rRanker</div>
        </footer>
      </div>
    </main>
  </div>
  ${runtime}
</body>
</html>`;
}
