import { decodeHtmlEntities } from '@maimai-score-hub/shared';
import { FONT_FAMILY } from './score-export.constants';
import { loadAsset } from './score-export.assets';
import type { UserNetProfile } from '../../users/user.types';
import type {
  CanvasContext,
  LoadRemoteImage,
} from './score-export.render-utils';
import { findRaPic } from './score-export.render-utils';

/**
 * Draw the profile header (plate, avatar, rating, name, title).
 * Draws at a fixed position (PX=14, starting Y=60).
 * Returns the Y position after the header (~200).
 */
export async function drawProfileHeader(
  ctx: CanvasContext,
  profile: UserNetProfile | null,
  rating: number,
  loadRemoteImage: LoadRemoteImage,
): Promise<number> {
  const PX = 14;
  await drawPlateAndIcon(ctx, PX);
  await drawAvatar(ctx, PX, profile, loadRemoteImage);
  await drawRating(ctx, PX, rating);
  await drawNameAndRanks(ctx, PX, profile, loadRemoteImage);
  drawTitle(ctx, PX, profile);
  return 200;
}

async function drawPlateAndIcon(ctx: CanvasContext, PX: number): Promise<void> {
  const plate = await loadAsset('UI_Plate_300501.png');
  if (plate) {
    ctx.drawImage(plate, PX, 60, 800, 130);
  }

  const defaultIcon = await loadAsset('UI_Icon_309503.png');
  if (defaultIcon) {
    ctx.drawImage(defaultIcon, PX + 5, 65, 120, 120);
  }
}

async function drawAvatar(
  ctx: CanvasContext,
  PX: number,
  profile: UserNetProfile | null,
  loadRemoteImage: LoadRemoteImage,
): Promise<void> {
  if (profile?.avatarUrl) {
    const avatarImg = await loadRemoteImage(profile.avatarUrl);
    if (avatarImg) {
      ctx.drawImage(avatarImg, PX + 5, 65, 120, 120);
    }
  }
}

async function drawRating(
  ctx: CanvasContext,
  PX: number,
  rating: number,
): Promise<void> {
  const dxRatingBar = await loadAsset(findRaPic(rating));
  if (dxRatingBar) {
    ctx.drawImage(dxRatingBar, PX + 135, 72, 186, 35);
  }

  const ratingStr = String(rating).padStart(5, '0');
  for (let n = 0; n < ratingStr.length; n++) {
    const digitImg = await loadAsset(`UI_NUM_Drating_${ratingStr[n]}.png`);
    if (digitImg) {
      ctx.drawImage(digitImg, PX + 220 + 15 * n, 80, 17, 20);
    }
  }
}

async function drawNameAndRanks(
  ctx: CanvasContext,
  PX: number,
  profile: UserNetProfile | null,
  loadRemoteImage: LoadRemoteImage,
): Promise<void> {
  const nameBg = await loadAsset('Name.png');
  if (nameBg) {
    ctx.drawImage(nameBg, PX + 135, 115);
  }

  if (profile?.courseRankUrl) {
    const matchImg = await loadRemoteImage(profile.courseRankUrl);
    if (matchImg) {
      ctx.drawImage(matchImg, PX + 325, 120, 80, 32);
    }
  }

  if (profile?.classRankUrl) {
    const classImg = await loadRemoteImage(profile.classRankUrl);
    if (classImg) {
      ctx.drawImage(classImg, PX + 320, 60, 90, 54);
    }
  } else {
    const defaultClass = await loadAsset('UI_FBR_Class_00.png');
    if (defaultClass) {
      ctx.drawImage(defaultClass, PX + 320, 60, 90, 54);
    }
  }

  const shougou = await loadAsset('UI_CMN_Shougou_Rainbow.png');
  if (shougou) {
    ctx.drawImage(shougou, PX + 135, 160, 270, 27);
  }

  ctx.font = `25px ${FONT_FAMILY}`;
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  ctx.fillStyle = 'rgba(0,0,0,1)';
  ctx.fillText(
    profile?.username ? decodeHtmlEntities(profile.username) : '',
    PX + 145,
    135,
  );
}

function drawTitle(
  ctx: CanvasContext,
  PX: number,
  profile: UserNetProfile | null,
): void {
  if (profile?.title) {
    ctx.font = `13px ${FONT_FAMILY}`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillStyle = 'rgba(0,0,0,0.8)';
    ctx.fillText(decodeHtmlEntities(profile.title), PX + 270, 173);
  }
}

export async function drawFooter(
  ctx: CanvasContext,
  width: number,
  footerY: number,
): Promise<void> {
  const designBar = await loadAsset('design.png');
  if (designBar) {
    ctx.drawImage(designBar, 300, footerY, 800, 72);
  }
  ctx.font = `22px ${FONT_FAMILY}`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.lineWidth = 5;
  ctx.strokeStyle = 'rgba(255,255,255,1)';
  const creditText = 'Generated by MaiScoreHub';
  ctx.strokeText(creditText, width / 2, footerY + 40);
  ctx.fillStyle = 'rgba(124,129,255,1)';
  ctx.fillText(creditText, width / 2, footerY + 40);
}
