import { JSDOM } from 'jsdom';
import { describe, expect, it } from 'vitest';
import type { ScoreRecord } from '@/domain/models';
import {
  buildPhigrosBestImageAppHtml,
} from '@/features/phigros-best-image/build-phigros-best-image-app-html';
import { paginatePhigrosBestImageSections } from '@/features/phigros-best-image/phigros-best-image';
import { suggestion } from '@/features/phigros-best-image/build-phigros-best-image-html';

function renderedText(html: string): string {
  const dom = new JSDOM(html);
  dom.window.document.querySelectorAll('script, style').forEach((node) => node.remove());
  const text = dom.window.document.body.textContent ?? '';
  dom.window.close();
  return text;
}

function record(id: string, overrides: Partial<ScoreRecord> = {}): ScoreRecord {
  return {
    songId: id, title: `歌曲 ${id}`, type: 'SD', levelIndex: 2, level: 'IN', difficulty: 'expert',
    difficultyConstant: 14, achievements: 98, dxScore: 980000, rating: 13, fc: null, fs: null,
    rate: 'v', version: 'current', ...overrides,
  };
}

const TEMPLATE_ASSETS = {
  css: '.song{width:360px}', dataIconUrl: 'data:image/png;base64,data', fallbackBackgroundUrl: 'file:///bg.png', fallbackAvatarUrl: 'file:///avatar.png',
  challengeIconUrls: Array.from({ length: 6 }, (_, index) => `data:image/png;base64,c${index}`),
  ratingIconUrls: { F: 'file:///F.png', V: 'file:///V.png', FC: 'file:///FC.png', phi: 'file:///phi.png' },
  allowingReadAccessToUrl: 'file:///',
};

function buildAppHtml({
  width = 1080,
  records = [record('x')],
  overrides = {},
}: {
  width?: 1080 | 1440 | 2160;
  records?: ScoreRecord[];
  overrides?: Partial<Parameters<typeof buildPhigrosBestImageAppHtml>[0]>;
} = {}) {
  const page = paginatePhigrosBestImageSections([{ id: 'b27', title: 'Best27', records }])[0]!;
  return buildPhigrosBestImageAppHtml({
    type: 'custom', width, page, playerName: '尘言', rks: '16.1053', dataAmount: '386MiB 289KiB',
    challenge: '42', challengeModeRank: 442, syncedAt: '2026/07/23 01:00:00',
    progress: { cleared: [0, 31, 221, 39], fullCombo: [0, 12, 111, 4], phi: [0, 4, 16, 2] },
    titles: Object.fromEntries(records.map((item) => [item.songId, item.title])),
    illustrations: Object.fromEntries(records.map((item) => [item.songId, 'data:image/png;base64,cover'])),
    avatarDataUri: 'data:image/png;base64,avatar',
    backgroundDataUri: 'data:image/png;base64,background',
    templateAssets: TEMPLATE_ASSETS,
    ...overrides,
  });
}

describe('buildPhigrosBestImageAppHtml', () => {
  it('渲染总览式头部（头像 + RKS/课题模式卡 + 统计表同行）与署名', () => {
    const html = buildAppHtml();
    expect(html).toContain('src="data:image/png;base64,avatar"');
    expect(html).toContain('<div class="name-card-bg" aria-hidden="true"><img class="name-card-image" alt="" src="data:image/png;base64,background"><div class="name-card-veil"></div></div>');
    expect(html).toContain('尘言');
    expect(html).toContain('RKS');
    expect(html).toContain('16.1053');
    expect(html).toContain('386MiB 289KiB');
    expect(html).toContain('课题模式');
    expect(html).toContain('42');
    expect(renderedText(html)).toContain('EZHDINAT');
    expect(renderedText(html)).toContain('C03122139');
    expect(renderedText(html)).toContain('Phi04162');
    expect(html).not.toContain('2026/07/23');
    expect(html).not.toContain('base64,c4');
    expect(html).toContain('src="data:image/png;base64,background"');
    expect(html).toContain('Designed by EgawaHokori. Data from TapTap.');
    expect(html).toContain('Generated by rRanker');
  });

  it('3 列卡片以难度深色为主题色，定数->RKS 与评价标签对齐已有样式', () => {
    const html = buildAppHtml();
    expect(html).toContain('<div class="card-art" aria-hidden="true"><img class="card-art-image" alt="" src="data:image/png;base64,cover"><div class="card-art-veil"></div></div>');
    expect(html).toContain('14.0-&gt;13.00');
    expect(html).toContain('980000');
    expect(html).toContain('98.00%');
    expect(html).toContain('V');
    expect(html).toContain('98.85%');
    expect(html).toContain('歌曲 x');
  });

  it('phi 满成绩与 FC 成绩的评价徽章对齐 PhigrosRateBadge', () => {
    const phi = record('p', { achievements: 100, dxScore: 1_000_000, fc: 'ap', rate: 'phi' });
    const phiPage = paginatePhigrosBestImageSections([{ id: 'phi3', title: 'Phi3', records: [phi] }])[0]!;
    const phiHtml = buildPhigrosBestImageAppHtml({
      type: 'best30', width: 1080, page: phiPage, playerName: '尘言', rks: '16.1053', dataAmount: '386MiB 289KiB',
      challenge: '42', challengeModeRank: 442, syncedAt: '2026/07/23 01:00:00',
      progress: { cleared: [0, 0, 0, 0], fullCombo: [0, 0, 0, 0], phi: [0, 0, 0, 0] },
      titles: { p: '歌曲 p' }, illustrations: { p: 'data:image/png;base64,cover' },
      avatarDataUri: null, backgroundDataUri: null,
      templateAssets: TEMPLATE_ASSETS,
    });
    expect(phiHtml).toContain('φ');
    expect(phiHtml).toContain('无法推分');

    const fc = record('f', { fc: 'fc', rate: 'v' });
    const fcHtml = buildAppHtml({ records: [fc] });
    expect(fcHtml).toContain('V');
  });

  it('缺失头像、背景与曲绘时回退占位', () => {
    const html = buildAppHtml({ records: [record('x', { title: '无封面' })], overrides: {
      avatarDataUri: null,
      backgroundDataUri: null,
      illustrations: { x: null },
    } });
    expect(html).toContain('尘');
    expect(html).toContain('♪');
    expect(html).not.toContain('src="data:image/png;base64,cover"');
  });

  it('转义长文本并输出三档分辨率', () => {
    for (const width of [1080, 1440, 2160] as const) {
      const html = buildAppHtml({
        width,
        records: [record('x', { title: '<script>alert(1)</script>' })],
        overrides: { playerName: '<玩家>', rks: '15.4321' },
      });
      expect(html).toContain(`width=${width}, initial-scale=1`);
      expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
      expect(html).toContain('&lt;玩家&gt;');
      expect(html).toContain('15.4321');
    }
  });

  it('空成绩输出空态并支持多页标记', () => {
    const single = buildAppHtml({ records: [] });
    expect(single).toContain('暂无符合条件的成绩');
    const page = paginatePhigrosBestImageSections([{ id: 'b27', title: 'Best27', records: [record('x')] }])[0]!;
    const multi = buildPhigrosBestImageAppHtml({
      type: 'custom', width: 1080, page: { ...page, pageCount: 3, pageIndex: 1 },
      playerName: '尘言', rks: '16.1053', dataAmount: '386MiB 289KiB', challenge: '42', challengeModeRank: 442,
      syncedAt: '2026/07/23 01:00:00', progress: { cleared: [0, 0, 0, 0], fullCombo: [0, 0, 0, 0], phi: [0, 0, 0, 0] },
      titles: { x: '歌曲 x' }, illustrations: { x: null }, avatarDataUri: null, backgroundDataUri: null,
      templateAssets: TEMPLATE_ASSETS,
    });
    expect(multi).toContain('第 2 / 3 页');
  });

  it('推分建议按定数、参考 RKS 与玩家 RKS 计算', () => {
    expect(suggestion(0, 15, 16, true)).toEqual({ label: '无法推分', type: null });
    expect(suggestion(15, 15, 16, true)).toEqual({ label: '100.00%', type: 5 });
    expect(suggestion(15.4, 15, 16, false)).toEqual({ label: '99.63%', type: 3 });
    const html = buildAppHtml({ records: [record('x', { achievements: 96, rating: 14 })] });
    expect(html).toContain('%');
  });
});
