import { describe, expect, it } from 'vitest';
import type { ScoreRecord } from '@/domain/models';
import {
  buildPhigrosBestImageAppHtml,
} from '@/features/phigros-best-image/build-phigros-best-image-app-html';
import { paginatePhigrosBestImageSections } from '@/features/phigros-best-image/phigros-best-image';
import { suggestion } from '@/features/phigros-best-image/build-phigros-best-image-html';

function record(id: string, overrides: Partial<ScoreRecord> = {}): ScoreRecord {
  return {
    songId: id, title: `歌曲 ${id}`, type: 'SD', levelIndex: 2, level: 'IN', difficulty: 'expert',
    difficultyConstant: 14, achievements: 98, dxScore: 980000, rating: 13, fc: null, fs: null,
    rate: 'v', version: 'current', ...overrides,
  };
}

const TEMPLATE_ASSETS = {
  css: '.song{width:360px}', dataIconUrl: 'data:image/png;base64,data', fallbackBackgroundUrl: 'file:///bg.png', fallbackAvatarUrl: 'file:///avatar.png',
  challengeIconUrls: Array.from({ length: 6 }, (_, index) => `data:image/png;base64,c${index}`),
  ratingIconUrls: { F: 'file:///F.png', V: 'file:///V.png', FC: 'file:///FC.png', phi: 'file:///phi.png' },
  allowingReadAccessToUrl: 'file:///',
};

function buildAppHtml({
  width = 1080,
  records = [record('x')],
  overrides = {},
}: {
  width?: 1080 | 1440 | 2160;
  records?: ScoreRecord[];
  overrides?: Partial<Parameters<typeof buildPhigrosBestImageAppHtml>[0]>;
} = {}) {
  const page = paginatePhigrosBestImageSections([{ id: 'b27', title: 'Best27', records }])[0]!;
  return buildPhigrosBestImageAppHtml({
    type: 'custom', width, page, playerName: '尘言', rks: '16.1053', dataAmount: '386MiB 289KiB',
    challenge: '42', challengeModeRank: 442, syncedAt: '2026/07/23 01:00:00',
    progress: { cleared: [0, 31, 221, 39], fullCombo: [0, 12, 111, 4], phi: [0, 4, 16, 2] },
    titles: Object.fromEntries(records.map((item) => [item.songId, item.title])),
    illustrations: Object.fromEntries(records.map((item) => [item.songId, 'data:image/png;base64,cover'])),
    avatarDataUri: 'data:image/png;base64,avatar',
    backgroundDataUri: 'data:image/png;base64,background',
    templateAssets: TEMPLATE_ASSETS,
    ...overrides,
  });
}

describe('buildPhigrosBestImageAppHtml', () => {
  it('渲染总览式头部（头像 + RKS/课题模式卡 + 统计表同行）与署名', () => {
    const html = buildAppHtml();
    expect(html).toContain('data-rating-style="app"');
    expect(html).toContain('class="app-header"');
    expect(html).not.toContain('class="profile-banner"');
    expect(html).toContain('class="header-left"');
    expect(html).toContain('class="identity-row"');
    expect(html).toContain('src="data:image/png;base64,avatar"');
    expect(html).toContain('<div class="name-card-bg" aria-hidden="true"><img class="name-card-image" alt="" src="data:image/png;base64,background"><div class="name-card-veil"></div></div>');
    expect(html).toContain('.name-card-veil{position:absolute;inset:0;background:rgba(255,255,255,.68)');
    expect(html).toContain('<span class="name-card-text">尘言</span>');
    expect(html).toContain('class="rating-card"');
    expect(html).toContain('<div class="rating-label">RKS</div>');
    expect(html).toContain('<div class="rating-value">16.1053</div>');
    expect(html).toContain('<div class="rating-meta">386MiB 289KiB</div>');
    expect(html).toContain('<div class="badge-title">课题模式</div>');
    expect(html).toContain('<div class="badge-value">42</div>');
    expect(html).toContain('--rating-border:linear-gradient(90deg,#8E6A1C 0%,#6F4D12 100%)');
    expect(html).toContain('--rating-fill:linear-gradient(90deg,#FBE7A1 0%,#F0C761 52%,#DEAA3B 100%)');
    expect(html).toContain('class="stats-card"');
    expect(html).toContain('.stats-card{flex:1;min-width:0;display:flex;flex-direction:column;overflow:hidden;border:1px solid rgba(255,255,255,.82);border-radius:18px;background:rgba(255,255,255,.55)');
    expect(html).toContain('grid-template-columns:80px repeat(4,minmax(0,1fr))');
    expect(html).toContain('font:800 30px/1 system-ui,sans-serif');
    expect(html).toContain('<div class="stats-line stats-head"><span>进度</span><span>EZ</span><span>HD</span><span>IN</span><span>AT</span></div>');
    expect(html).toContain('<span>C</span><span>0</span><span>31</span><span>221</span><span>39</span>');
    expect(html).toContain('<span>Phi</span><span>0</span><span>4</span><span>16</span><span>2</span>');
    expect(html).not.toContain('2026/07/23');
    expect(html).not.toContain('base64,c4');
    expect(html).not.toContain('dataIconUrl');
    expect(html).toContain('src="data:image/png;base64,background"');
    expect(html).toContain('class="image-footer"');
    expect(html).toContain('Designed by EgawaHokori. Data from TapTap.');
    expect(html).toContain('<div>Generated by rRanker</div>');
  });

  it('3 列卡片以难度深色为主题色，定数->RKS 与评价标签对齐已有样式', () => {
    const html = buildAppHtml();
    expect(html).toContain('grid-template-columns:repeat(3,minmax(0,1fr))');
    expect(html).toContain('--card-bg:#D84B68;--card-fg:#FFFFFF');
    expect(html).toContain('<div class="card-art" aria-hidden="true"><img class="card-art-image" alt="" src="data:image/png;base64,cover"><div class="card-art-veil"></div></div>');
    expect(html).toContain('.card-art-veil{position:absolute;inset:0;background:var(--card-bg);opacity:.8;-webkit-backdrop-filter:blur(');
    expect(html).not.toContain('level-badge');
    expect(html).not.toContain('IN&ensp;');
    expect(html).toContain('>14.0-&gt;13.00</span>');
    expect(html).toContain('<strong class="achievement">980000</strong>');
    expect(html).toContain('98.00%');
    expect(html).toContain('>V</span>');
    expect(html).toContain('--rate-bg:#4B5563');
    expect(html).not.toContain('class="avg-ribbon"');
    expect(html).toContain('<span class="suggest">98.85%</span>');
    expect(html).toContain('>歌曲 x</strong>');
  });

  it('phi 满成绩与 FC 成绩的评价徽章对齐 PhigrosRateBadge', () => {
    const phi = record('p', { achievements: 100, dxScore: 1_000_000, fc: 'ap', rate: 'phi' });
    const phiPage = paginatePhigrosBestImageSections([{ id: 'phi3', title: 'Phi3', records: [phi] }])[0]!;
    const phiHtml = buildPhigrosBestImageAppHtml({
      type: 'best30', width: 1080, page: phiPage, playerName: '尘言', rks: '16.1053', dataAmount: '386MiB 289KiB',
      challenge: '42', challengeModeRank: 442, syncedAt: '2026/07/23 01:00:00',
      progress: { cleared: [0, 0, 0, 0], fullCombo: [0, 0, 0, 0], phi: [0, 0, 0, 0] },
      titles: { p: '歌曲 p' }, illustrations: { p: 'data:image/png;base64,cover' },
      avatarDataUri: null, backgroundDataUri: null,
      templateAssets: TEMPLATE_ASSETS,
    });
    expect(phiHtml).toContain('>φ</span>');
    expect(phiHtml).toContain('--rate-bg:#FFF7E6');
    expect(phiHtml).toContain('<span class="suggest suggest-empty">无法推分</span>');
    expect(phiHtml).not.toContain('class="avg-ribbon"');

    const fc = record('f', { fc: 'fc', rate: 'v' });
    const fcHtml = buildAppHtml({ records: [fc] });
    expect(fcHtml).toContain('>V</span>');
    expect(fcHtml).toContain('--rate-bg:#E0F2FE');
    expect(fcHtml).not.toContain('--rate-bg:#ECFDF5');
  });

  it('缺失头像、背景与曲绘时回退占位', () => {
    const html = buildAppHtml({ records: [record('x', { title: '无封面' })], overrides: {
      avatarDataUri: null,
      backgroundDataUri: null,
      illustrations: { x: null },
    } });
    expect(html).toContain('<div class="avatar-fallback">尘</div>');
    expect(html).not.toContain('class="background-image"');
    expect(html).toContain('linear-gradient(145deg,#EEF2F8 0%,#E7EDF5 52%,#F5F7FA 100%)');
    expect(html).not.toContain('class="name-card-bg"');
    expect(html).toContain('<span class="jacket-fallback">♪</span>');
    expect(html).not.toContain('class="card-art"');
    expect(html).not.toContain('src="data:image/png;base64,cover"');
  });

  it('转义长文本并输出三档分辨率', () => {
    for (const width of [1080, 1440, 2160] as const) {
      const html = buildAppHtml({
        width,
        records: [record('x', { title: '<script>alert(1)</script>' })],
        overrides: { playerName: '<玩家>', rks: '15.4321' },
      });
      expect(html).toContain(`width=${width}, initial-scale=1`);
      expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
      expect(html).toContain('&lt;玩家&gt;');
      expect(html).toContain('15.4321');
      expect(html).not.toContain('createdbox');
      expect(html).not.toContain('phi-plugin');
    }
  });

  it('空成绩输出空态并支持多页标记', () => {
    const single = buildAppHtml({ records: [] });
    expect(single).toContain('<div class="empty-scores">暂无符合条件的成绩</div>');
    const page = paginatePhigrosBestImageSections([{ id: 'b27', title: 'Best27', records: [record('x')] }])[0]!;
    const multi = buildPhigrosBestImageAppHtml({
      type: 'custom', width: 1080, page: { ...page, pageCount: 3, pageIndex: 1 },
      playerName: '尘言', rks: '16.1053', dataAmount: '386MiB 289KiB', challenge: '42', challengeModeRank: 442,
      syncedAt: '2026/07/23 01:00:00', progress: { cleared: [0, 0, 0, 0], fullCombo: [0, 0, 0, 0], phi: [0, 0, 0, 0] },
      titles: { x: '歌曲 x' }, illustrations: { x: null }, avatarDataUri: null, backgroundDataUri: null,
      templateAssets: TEMPLATE_ASSETS,
    });
    expect(multi).toContain('第 2 / 3 页');
  });

  it('推分建议按定数、参考 RKS 与玩家 RKS 计算', () => {
    expect(suggestion(0, 15, 16, true)).toEqual({ label: '无法推分', type: null });
    expect(suggestion(15, 15, 16, true)).toEqual({ label: '100.00%', type: 5 });
    expect(suggestion(15.4, 15, 16, false)).toEqual({ label: '99.63%', type: 3 });
    const html = buildAppHtml({ records: [record('x', { achievements: 96, rating: 14 })] });
    expect(html).toContain('class="suggest');
    expect(html).toContain('%</span>');
  });
});
