export const REQUEST_PRIORITY_BACKGROUND = 0;
export const REQUEST_PRIORITY_RECENT_EVENT = 1;
export const REQUEST_PRIORITY_UPDATE_SCORE = 2;
export const REQUEST_PRIORITY_USER_AUTH_REQUEST = 3;
export const REQUEST_PRIORITY_IMMEDIATE = 4;
